# Generated by Django 5.0.1 on 2024-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Новость")),
                ("published", models.DateTimeField(verbose_name="Дата публикации")),
            ],
        ),
    ]
